[package]
name = "tee_llm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
llama_cpp ={ path = "../llama_cpp-rs/crates/llama_cpp", version = "0.3.2"}

[lints]
workspace = true
