[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
derive-where = "1.2.7"
serde_json = "1.0.114"
serde = { version = "1.0.195", features = ["derive"] }

[lints]
workspace = true
